version: '3'

services:
  db:
    image: postgres:12
    environment:
      - POSTGRES_DB=$DATABASE_NAME
      - POSTGRES_USER=$DATABASE_USER
      - POSTGRES_PASSWORD=$DATABASE_PASSWORD
    ports:
      - 5432:5432

  server:
    build: ./server
    working_dir: /var/app
    command: gow run .
    environment:
      - JWT_SECRET=$JWT_SECRET
      - JWT_EXPIRATION_TIME_IN_S=$JWT_EXPIRATION_TIME_IN_S
      - DATABASE_URL=postgres://$DATABASE_USER:$DATABASE_PASSWORD@db:5432/$DATABASE_NAME?sslmode=disable
    depends_on:
      - db
    ports:
      - '8080:8080'
    volumes:
      - './server:/var/app'
