version: '3'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=$DATABASE_NAME
      - POSTGRES_USER=$DATABASE_USER
      - POSTGRES_PASSWORD=$DATABASE_PASSWORD
    ports:
      - 5432:5432

  server:
    build: ./server
    working_dir: /var/app
    command: gow run .
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_NAME
      - DATABASE_USER
      - DATABASE_PASSWORD
    depends_on:
      - db
    ports:
      - '8080:8080'
    volumes:
      - './server:/var/app'
