version: '3'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=budgie
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432

  db_test:
    image: postgres
    environment:
      - POSTGRES_DB=budgie_test
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5433:5432

