FROM bitnami/golang:latest

RUN go get -u github.com/gin-gonic/gin
RUN go get -u github.com/jmoiron/sqlx
RUN go get -u github.com/lib/pq
RUN go get -u github.com/gin-contrib/cors
RUN go get -u github.com/dgrijalva/jwt-go
RUN go get -u golang.org/x/crypto/bcrypt

RUN go get -u github.com/mitranim/gow